spring.application.name=just-rent-it-by-np
spring.datasource.url=jdbc:mysql://localhost:3306/just_rent_it_by_np
spring.datasource.username=root
spring.datasource.password=@Namami128


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8081
